FROM rocker/tidyverse:3.5.1
RUN R -e 'install.packages("remotes")'
RUN R -e 'remotes::install_github("r-lib/remotes", ref = "97bbf81")'
RUN R -e 'remotes::install_cran("here")'
RUN R -e 'remotes::install_cran("shiny")'
RUN R -e 'remotes::install_cran("shinyjs")'
RUN R -e 'remotes::install_cran("sf")'
RUN R -e 'remotes::install_cran("leaflet")'
RUN R -e 'remotes::install_cran("leaflet.extras")'
RUN R -e 'remotes::install_cran("readr")'
RUN R -e 'remotes::install_cran("stringr")'
RUN R -e 'remotes::install_cran("magrittr")'
RUN R -e 'remotes::install_cran("lubridate")'
RUN R -e 'remotes::install_cran("dplyr")'
RUN R -e 'remotes::install_cran("htmlwidgets")'
RUN R -e 'remotes::install_cran("DT")'
RUN R -e 'remotes::install_cran("tidyr")'
RUN R -e 'remotes::install_cran("plotly")'
RUN R -e 'remotes::install_cran("markdown")'
RUN R -e 'remotes::install_cran("bsplus")'
RUN R -e 'remotes::install_cran("pkgload")'
COPY bchousing_*.tar.gz /app.tar.gz
RUN R -e 'remotes::install_local("/app.tar.gz")'
EXPOSE 80
CMD R -e "options('shiny.port'=80,shiny.host='0.0.0.0');bchousing::run_app()"
