---
title: "Victoria Population Pyramid"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

Packages

```{r}

library(tidyverse)
library(feather)


```


Data

```{r}

#PopData_source <- read_csv("E:/github/Census_wrangling/Census_wrangle/data/2016_age-sex/CT_data__age_5yr_Victoria_mun.csv")

PopData_source <- read_feather("../../data/2016_age-sex/CT_data__age_5yr_Victoria_mun.feather")

```



Summarize for Victoria City

```{r}

final.pop.raw <- PopData_source %>%
  group_by(age) %>%
  summarise(male = sum(pop_male),
            female = sum(pop_female)) %>%
  gather("male", "female", key = "sex", value = "pop")


final.pop.raw


# Normalize to age bins as a share of the total population in that year.

final.pop <- final.pop.raw %>%
#  group_by(sex) %>%
  mutate(poppct = pop / sum(pop)) %>%
  ungroup() %>%
  mutate("neighbourhood" = "Victoria (City)")


final.pop

```


```{r}

ggplot(final.pop, aes(x = age, fill = sex)) +
  geom_bar(aes(y = poppct), stat = "identity", position = "identity",
           color = "gray10", size = 0.1,
           data = filter(final.pop, sex == "male")) +
  geom_bar(aes(y = -1 * poppct), stat = "identity", position = "identity",
           color = "gray10", size = 0.1,
           data = filter(final.pop, sex == "female")) +
#  geom_text(aes(label = year), y = 0.06, x = 19.5, family = "minion",
#            size = 3) +
#  facet_grid(geo ~ year, scales = "fixed") +
  coord_flip() +
  scale_fill_brewer(palette = "Pastel1") +
  labs(x = NULL, y = NULL, title = NULL, fill = NULL) +
  theme_bw()

```



