---
title: "NHS Shelter Cost Ratio"
author: Sasha Bogdanovic
output:
  html_document: default
html_notebook: default
editor_options:
  chunk_output_type: inline
---
  
## Load Packages and required files

```{r}
library(tidyverse)
library(feather)
library(stringr)
library(plotly)
library(htmltools)
library(DT)
library(knitr)

geoCMA <- readRDS("../data/geoCMA.rds")
source("../modules/chartFormat.R")
```


## Load Data

Read data tables from csv file and wrangle geography column to filter out non-BC geographies

```{r}
data <- read_csv("./NHS_99-014-X2011031_sheltercostratio.csv")

# Function to extract CMA code from Geography
extractCMA = function(x) {
  sapply(x, function(x){
    x = str_split(x, " \\(", n = 2, simplify = TRUE)
    y = str_split(x[2], "\\)", n = -1, simplify = TRUE)
    return(as.integer(y[1]))
  })
}

# Join to CMA geo-reference
data <- data %>%
  mutate(CMAuid = extractCMA(Geography)) %>%
  filter(!str_detect(CMAuid, "part")) %>%
  inner_join(geoCMA)

# Mutate to add percentages columns
data <- data %>%
  mutate(total_applicable = `Less than 15%` + `15% to less than 30%` + `30% to less than 50%` + `50% or more`) %>%
  mutate(less_than_15_percent = round(`Less than 15%` / total_applicable * 100, digits = 2)) %>%
  mutate(between_15_and_30_percent = round(`15% to less than 30%` / total_applicable * 100, digits = 2)) %>%
  mutate(between_30_and_50_percent = round(`30% to less than 50%` / total_applicable * 100, digits = 2)) %>%
  mutate(more_than_50_percent = round(`50% or more` / total_applicable * 100, digits = 2)) %>%
  mutate(not_applicable_percent = round(`Not applicable (private households with a household total income less than or equal to zero)` / `Total - Shelter-cost-to-income ratio` * 100)) %>%
  arrange(desc(more_than_50_percent), desc(between_30_and_50_percent), desc(between_15_and_30_percent))

```

## Data Visualization
### Data tables
```{r}
data %>%
     DT::datatable(class='compact stripe hover row-border order-column',rownames=FALSE,options= list(paging = TRUE, searching = TRUE,info=FALSE))

```

### Stacked chart
```{r}
# Some chart options
topLabels <- c('More than 50%', 'Between 30 and 50%', 'Between 15 and 30%', 'Less than 15%') #, 'Not applicable')
labelPositions <- c(
  data[1,"more_than_50_percent"] / 2, 
  data[1,"more_than_50_percent"] + data[1,"between_30_and_50_percent"] / 2, 
  data[1,"more_than_50_percent"] + data[1,"between_30_and_50_percent"] + data[1,"between_15_and_30_percent"] / 2,
  data[1,"more_than_50_percent"] + data[1,"between_30_and_50_percent"] + data[1,"between_15_and_30_percent"] + data[1,"less_than_15_percent"] / 2
)

# Reorder data for plotly
data$CMAname <- factor(data$CMAname, levels = unique(data$CMAname)[order(data$more_than_50_percent, data$between_30_and_50_percent, data$between_15_and_30_percent, decreasing = FALSE)])

p <- plot_ly(data, x = ~more_than_50_percent, y = ~CMAname, type = 'bar', orientation = 'h',
             marker = list(color = colCommercial,
                           line = list(color = 'rgb(248, 248, 249)', width = 1), text = "%", hoverinfo="x+y+text")) %>%
  add_trace(x = ~between_30_and_50_percent, marker = list(color = colFarms)) %>%
  add_trace(x = ~between_15_and_30_percent, marker = list(color = colMultiFam)) %>%
  add_trace(x = ~less_than_15_percent, marker = list(color = colSingleFam)) %>%
  layout(xaxis = list(title = "",
                      showgrid = FALSE,
                      showline = FALSE,
                      showticklabels = FALSE,
                      zeroline = FALSE,
                      domain = c(0.15, 1)),
         yaxis = list(title = "",
                      showgrid = FALSE,
                      showline = FALSE,
                      showticklabels = FALSE,
                      zeroline = FALSE),
         barmode = 'stack',
         paper_bgcolor = 'rgb(248, 248, 255)', plot_bgcolor = 'rgb(248, 248, 255)',
         margin = list(l = 120, r = 10, t = 140, b = 80),
         showlegend = FALSE) %>%
  # labeling the y-axis
  add_annotations(xref = 'paper', yref = 'y', x = 0.14, y = ~CMAname,
                  xanchor = 'right',
                  text = ~CMAname,
                  font = list(family = 'Arial', size = 12,
                              color = 'rgb(67, 67, 67)'),
                  showarrow = FALSE, align = 'right') %>%
  # labeling the percentages of each bar (x_axis)
  add_annotations(xref = 'x', yref = 'y',
                  x = ~(more_than_50_percent / 2), y = ~CMAname,
                  text = ~paste(more_than_50_percent, '%'),
                  font = list(family = 'Arial', size = 12,
                              color = 'rgb(67, 67, 67)'),
                  showarrow = FALSE) %>%
  add_annotations(xref = 'x', yref = 'y',
                  x = ~(more_than_50_percent + between_30_and_50_percent / 2), y = ~CMAname,
                  text = ~paste(between_30_and_50_percent, '%'),
                  font = list(family = 'Arial', size = 12,
                              color = 'rgb(67, 67, 67)'),
                  showarrow = FALSE) %>%
  add_annotations(xref = 'x', yref = 'y',
                  x = ~(more_than_50_percent + between_30_and_50_percent + between_15_and_30_percent / 2), y = ~CMAname,
                  text = ~paste(between_15_and_30_percent, '%'),
                  font = list(family = 'Arial', size = 12,
                              color = 'rgb(67, 67, 67)'),
                  showarrow = FALSE) %>%
  add_annotations(xref = 'x', yref = 'y',
                  x = ~(more_than_50_percent + between_30_and_50_percent + between_15_and_30_percent + less_than_15_percent / 2), y = ~CMAname,
                  text = ~paste(less_than_15_percent, '%'),
                  font = list(family = 'Arial', size = 12,
                              color = 'rgb(67, 67, 67)'),
                  showarrow = FALSE) %>%
  # labeling the first Likert scale (on the top)
  add_annotations(xref = 'x', yref = 'paper',
                  x = labelPositions,
                  y = 1.03,
                  text = topLabels,
                  font = list(family = 'Arial', size = 12,
                              color = 'rgb(67, 67, 67)'),
                  showarrow = FALSE)

p
```