# Data Sources

BC Housing Data Visualization Platform uses the following datasets:
- Census Canada (years 2016, 2011 and 2006).
- Property Transfer Tax (2017 and 2016).

### Census Canada
Census data is provided by [Statistics Canada](http://www.statcan.gc.ca/)
and obtained through [CensusMapper API](https://censusmapper.ca/api) 
using [cancensus R package](https://github.com/mountainMath/cancensus).
- Statistics Canada. No date. 2006 Census of Canada (Provinces, Census Divisions, Municipalities) (database).
- Statistics Canada. No date. 2011 Census of Canada (Provinces, Census Divisions, Municipalities) (database).
- Statistics Canada. No date. 2016 Census of Canada (Provinces, Census Divisions, Municipalities) (database).

Statistics Canada provides a wealth of detail about the information collected in the Census. Some of the key pages are:

* [Census Program homepage](http://www12.statcan.gc.ca/census-recensement/index-eng.cfm)

* [Data products, 2016 Census](http://www12.statcan.gc.ca/census-recensement/2016/dp-pd/index-eng.cfm)

   - [Data tables, 2016 Census](http://www12.statcan.gc.ca/census-recensement/2016/dp-pd/dt-td/index-eng.cfm), grouped by topic, variable, and map 
   
   - [Reference materials, 2016 Census](http://www12.statcan.gc.ca/census-recensement/2016/ref/index-eng.cfm): concepts and definitions, reference guides and other materials
   
   - [Reference materials, 2016 Census: Housing](http://www12.statcan.gc.ca/census-recensement/2016/ref/98-501/98-501-x2016007-eng.cfm)



### Property Transfer Tax
Property transfer tax data relates to market transactions within the province.

Data is provided by the Province of B.C.'s Ministry of Finance,
licensed under [Open Government Licence - British Columbia](https://www2.gov.bc.ca/gov/content?id=A519A56BC2BF44E4A008B33FCF527F61).

The data is available for download at [B.C. Data Catalogue administered by DataBC](https://catalogue.data.gov.bc.ca/organization/property-taxation).
